// User
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS'
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE'

// Session
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE'
export const LOGOUT = 'LOGOUT'

// Alert
export const SUCCESS = 'ALERT_SUCCESS'
export const ERROR = 'ALERT_ERROR'
export const CLEAR = 'ALERT_CLEAR'

// StakeAddresses/:username
export const REQUEST_USER_STAKES = 'REQUEST_USER_STAKE_ADDRESSES'
export const REQUEST_USER_STAKES_SUCCESS = 'REQUEST_USER_STAKE_ADDRESSES'
export const REQUEST_USER_STAKES_FAILURE = 'REQUEST_USER_STAKES_FAILURE'

// Epochs
export const REQUEST_LAST_EPOCH = 'REQUEST_LAST_EPOCH'
export const REQUEST_LAST_EPOCH_SUCCESS = 'REQUEST_LAST_EPOCH_SUCCESS'
export const REQUEST_LAST_EPOCH_FAILURE = 'REQUEST_LAST_EPOCH_FAILURE'