// User
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS'
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE'

// Session
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE'
export const LOGOUT = 'LOGOUT'

// Alert
export const SUCCESS = 'ALERT_SUCCESS'
export const ERROR = 'ALERT_ERROR'
export const CLEAR = 'ALERT_CLEAR'

// EpochStake/:username
export const REQUEST_USER_EPOCH_STAKES = 'REQUEST_USER_EPOCH_STAKES'
export const REQUEST_USER_EPOCH_STAKES_SUCCESS = 'REQUEST_USER_EPOCH_STAKES_SUCCESS'
export const REQUEST_USER_EPOCH_STAKES_FAILURE = 'REQUEST_USER_EPOCH_STAKES_FAILURE'

export const REQUEST_EPOCH_STAKE = 'REQUEST_EPOCH_STAKE'
export const REQUEST_EPOCH_STAKE_SUCCESS = 'REQUEST_EPOCH_STAKE_SUCCESS'
export const REQUEST_EPOCH_STAKE_FAILURE = 'REQUEST_EPOCH_STAKE_FAILURE'

// StakeAddress/:username
export const ADD_USER_STAKE_REQUEST = 'ADD_USER_STAKE_REQUEST'
export const ADD_USER_STAKE_SUCCESS = 'ADD_USER_STAKE_SUCCESS'
export const ADD_USER_STAKE_FAILURE = 'ADD_USER_STAKE_FAILURE'

export const DELETE_USER_STAKE_REQUEST = 'DELETE_USER_STAKE_REQUEST'
export const DELETE_USER_STAKE_SUCCESS = 'DELETE_USER_STAKE_SUCCESS'
export const DELETE_USER_STAKE_FAILURE = 'DELETE_USER_STAKE_FAILURE'

// Pool
export const REQUEST_POOL_TICKERS = 'REQUEST_POOL_TICKERS'
export const REQUEST_POOL_TICKERS_SUCCESS = 'REQUEST_POOL_TICKERS_SUCCESS'


// Pool Compared Stakes
export const ADD_USER_POOL_HASH = 'ADD_USER_POOL_HASH'
export const ADD_USER_POOL_HASH_SUCCESS = 'ADD_USER_POOL_HASH_SUCCESS'
export const ADD_USER_POOL_HASH_FAILURE = 'ADD_USER_POOL_HASH_FAILURE'

export const REQUEST_USER_POOL_HASHES_EPOCH_STAKES = 'REQUEST_USER_POOL_HASHES_EPOCH_STAKES'
export const REQUEST_USER_POOL_HASHES_EPOCH_STAKES_SUCCESS = 'REQUEST_USER_POOL_HASHES_EPOCH_STAKES_SUCCESS'
export const REQUEST_USER_POOL_HASHES_EPOCH_STAKES_FAILURE = 'REQUEST_USER_POOL_HASHES_EPOCH_STAKES_FAILURE'
